---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: _drafts
  label: rascunhos
- type: heading
  label: JTemporal
- type: jekyll-posts
  label: Posts
  create: all
- type: jekyll-pages
  label: Pages
  create: all
- type: directory
  path: _hacktoberfest_projects
  label: Hacktoberfest
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - hacktober
- type: heading
  label: Tema
- type: directory
  path: _layouts
  label: Layouts
  create: documents
  match: "**/*"
  new_doc_ext: html
  templates:
  - empty
- type: directory
  path: _includes
  label: Includes
  create: documents
  match: "**/*"
  new_doc_ext: html
upload_dir: images
public_path: images
front_matter_path: "/images"
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --config _dev_config.yml --drafts
    --unpublished --future --port 8080 --host 0.0.0.0 -d _site
